-- ashrain.out — 재화 2종(Ⓟ Ash · Ⓓ Drop) 원장 + 개념 복습 기록 + 시험 응시 기록 (2026-09-15)
-- 앱은 이 파일이 적용되기 전에도 동작한다(잔액은 Ⓟ만, 복습 보상은 "준비 중", 시험 기록은 로컬 저장).
-- 적용 후: Ⓓ Drop 잔액·내역, 복습 완수 보상 적립, 시험 기록 DB 저장이 켜진다.

-- ── 1. 원장에 통화 구분 ─────────────────────────────────────────────────
-- 기존 행은 전부 Ⓟ(ash). Ⓟ = 유료 학습 기능(AI 한도 초과분)에 쓰는 재화, Ⓓ = 학습 활동 보상. 상호 교환 없음.
alter table public.point_ledger add column if not exists currency text not null default 'ash';
alter table public.point_ledger drop constraint if exists point_ledger_currency_check;
alter table public.point_ledger add constraint point_ledger_currency_check check (currency in ('ash', 'drop'));
create index if not exists point_ledger_user_cur on public.point_ledger (user_id, currency, created_at desc);
comment on column public.point_ledger.currency is 'ash = Ⓟ Ash 포인트(유료 기능), drop = Ⓓ Drop 포인트(활동 보상·숍). 교환 불가.';

create or replace function public.point_balance_of(p_uid uuid, p_currency text)
returns integer language sql stable security definer set search_path = public as $$
  select coalesce(sum(delta), 0)::int
    from public.point_ledger
   where user_id = p_uid and currency = p_currency
     and (auth.uid() is null or auth.uid() = p_uid or public.is_admin());
$$;

-- 기존 point_balance 는 Ⓟ 잔액으로 고정 (api/ai.js 의 차감 판정과 쿠폰 충전이 이 함수를 쓴다)
create or replace function public.point_balance(p_uid uuid)
returns integer language sql stable security definer set search_path = public as $$
  select public.point_balance_of(p_uid, 'ash');
$$;

-- ── 2. 개념 복습 기록 — Drop 적립의 근거 ─────────────────────────────────
-- 서버(api/review.js, service role)만 쓴다. 학생은 자기 기록 조회만.
create table if not exists public.concept_reviews (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  concept_id   text not null references public.concepts(id) on delete cascade,
  rank         integer,                                  -- 최근 읽은 순위 1(가장 최근)~5, 상한 산정용
  quiz         jsonb not null default '[]'::jsonb,       -- [{item_id}] 출제 문항 (정답은 서버가 다시 조회)
  started_at   timestamptz not null default now(),
  completed_at timestamptz,
  read_ms      integer,                                  -- 단계 읽기에 쓴 시간(클라 보고)
  score        integer,
  max          integer,
  reward       integer not null default 0,               -- 지급된 Ⓓ
  ledger_id    bigint
);
create index if not exists concept_reviews_user on public.concept_reviews (user_id, concept_id, completed_at desc);
alter table public.concept_reviews enable row level security;
drop policy if exists concept_reviews_own_select on public.concept_reviews;
drop policy if exists concept_reviews_admin on public.concept_reviews;
create policy concept_reviews_own_select on public.concept_reviews for select to authenticated using (auth.uid() = user_id);
create policy concept_reviews_admin on public.concept_reviews for all to authenticated using (is_admin()) with check (is_admin());

-- ── 3. 시험 응시 기록 — (개념묶음·mock·out) 3축 분석의 원천 ────────────────
create table if not exists public.test_runs (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  test_type    text not null,                            -- concept_set | unit | calc | sangwa | mock | ash | rain | out
  unit_id      text,
  concept_ids  text[] not null default '{}',
  item_ids     uuid[] not null default '{}',
  answers      jsonb not null default '[]'::jsonb,       -- [{item_id, answer, correct, elapsed_sec}]
  n            integer not null default 0,
  correct_n    integer not null default 0,
  score        integer,                                  -- 배점 합(mock 등) 또는 정답 수
  max          integer,
  started_at   timestamptz,
  finished_at  timestamptz not null default now(),
  elapsed_sec  integer,
  meta         jsonb not null default '{}'::jsonb        -- {timer, preset, device ...}
);
create index if not exists test_runs_user on public.test_runs (user_id, finished_at desc);
create index if not exists test_runs_type on public.test_runs (test_type, unit_id);
alter table public.test_runs enable row level security;
drop policy if exists test_runs_own_insert on public.test_runs;
drop policy if exists test_runs_own_select on public.test_runs;
drop policy if exists test_runs_admin on public.test_runs;
create policy test_runs_own_insert on public.test_runs for insert to authenticated with check (auth.uid() = user_id);
create policy test_runs_own_select on public.test_runs for select to authenticated using (auth.uid() = user_id);
create policy test_runs_admin on public.test_runs for all to authenticated using (is_admin()) with check (is_admin());
