-- ashrain.out — 학생앱 베타 (2026-09) 선택 마이그레이션
-- 앱은 이 파일 없이도 동작한다(테이블이 없으면 로컬 저장으로 대체). 아래를 SQL Editor 에서 실행하면
--   · 서술형 자가채점 결과가 DB 에 쌓이고 (essay_grades)
--   · 관리자가 attempts 를 볼 수 있다 (attempts_admin)
-- 문항형 오답노트는 DDL 없이 wrong_notes.image_path = 'item:<test_items.id>' 센티널로 저장한다.

-- ── 1. 서술형 자가채점 결과 ──────────────────────────────────────────────
create table if not exists public.essay_grades (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  item_id     uuid not null references public.test_items(id) on delete cascade,
  answer_text text,
  image_path  text,                                   -- notes/{uid}/essay/{uuid}.jpg
  scores      jsonb not null default '{}'::jsonb,     -- {marks, checks, perElement, correct, elapsedSec, verdict}
  total       integer not null default 0,
  max         integer not null default 0,
  correct     boolean generated always as ((scores->>'correct')::boolean) stored,
  created_at  timestamptz not null default now(),
  constraint essay_grades_answer_present check (answer_text is not null or image_path is not null),
  constraint essay_grades_total_range check (total >= 0 and total <= max)
);
comment on table public.essay_grades is '서술형 자가채점 — 학생이 루브릭으로 스스로 매긴 예상 점수. 공식 성적 아님.';
create index if not exists essay_grades_user_created on public.essay_grades (user_id, created_at desc);
create index if not exists essay_grades_item on public.essay_grades (item_id);
alter table public.essay_grades enable row level security;
drop policy if exists essay_grades_own_insert on public.essay_grades;
drop policy if exists essay_grades_own_select on public.essay_grades;
drop policy if exists essay_grades_admin on public.essay_grades;
create policy essay_grades_own_insert on public.essay_grades for insert to authenticated with check (auth.uid() = user_id);
create policy essay_grades_own_select on public.essay_grades for select to authenticated using (auth.uid() = user_id);
create policy essay_grades_admin on public.essay_grades for all to authenticated using (is_admin()) with check (is_admin());

-- ── 2. attempts 관리자 열람 (item_gen_v2 에서 미뤄 둔 정책) ─────────────────
drop policy if exists attempts_admin on public.attempts;
create policy attempts_admin on public.attempts for select to authenticated using (is_admin());

-- ── 3. (선택) 개념별 공개 문항 수 뷰 — 문항이 수만 건이 되면 count 호출 대신 이 뷰를 쓴다 ──
create or replace view public.v_live_item_counts as
select c as concept_id, unit_id, count(*)::int as n
from public.test_items, unnest(concept_ids) as c
where status = 'live'
group by c, unit_id;
grant select on public.v_live_item_counts to authenticated;
