-- ashrain.out — 3앱(학생·강사·학부모) 공용 게시판: 공지(notice) + 커뮤니티(community) (2026-09)
-- 앱은 이 파일이 적용되기 전에도 동작한다(목록 자리에 "게시판 준비 중" 카드로 강등).
-- 적용 후: 공지·커뮤니티 글/댓글, 작성자 스냅샷(username·role), 댓글 수 카운터가 켜진다.

-- ── 1. 글 ────────────────────────────────────────────────────────────────
create table if not exists public.posts (
  id          bigint generated by default as identity primary key,
  board       text not null check (board in ('notice', 'community')),
  user_id     uuid not null references auth.users(id) on delete cascade,
  author_name text,                                   -- 작성 시점 스냅샷 (profiles.username, 없으면 name)
  author_role text,                                   -- 작성 시점 스냅샷 (profiles.role)
  title       text not null check (char_length(title) <= 120),
  body        text not null,
  comment_n   integer not null default 0,             -- 댓글 수 (트리거가 증감)
  created_at  timestamptz not null default now()
);
create index if not exists posts_board_created_idx on public.posts (board, created_at desc);
comment on table public.posts is '학생·강사·학부모 3앱 공용 게시판 글. board=notice(학원 공지)|community(자유)';

-- ── 2. 댓글 ──────────────────────────────────────────────────────────────
create table if not exists public.post_comments (
  id          bigint generated by default as identity primary key,
  post_id     bigint not null references public.posts(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  author_name text,
  author_role text,
  body        text not null,
  created_at  timestamptz not null default now()
);
create index if not exists post_comments_post_idx on public.post_comments (post_id, created_at);

-- ── 3. 작성자 스냅샷 (BEFORE INSERT, 글·댓글 공용) ─────────────────────────
-- security definer: profiles RLS와 무관하게 username/role을 읽어 스냅샷.
-- user_id는 항상 auth.uid()로 강제(서비스 롤 호출 시에만 전달값 유지).
create or replace function public.board_author_snapshot()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.user_id := coalesce(auth.uid(), new.user_id);
  select coalesce(nullif(p.username, ''), p.name), p.role
    into new.author_name, new.author_role
    from public.profiles p
   where p.id = new.user_id;
  return new;
end $$;

drop trigger if exists posts_author_snapshot on public.posts;
create trigger posts_author_snapshot
  before insert on public.posts
  for each row execute function public.board_author_snapshot();

drop trigger if exists post_comments_author_snapshot on public.post_comments;
create trigger post_comments_author_snapshot
  before insert on public.post_comments
  for each row execute function public.board_author_snapshot();

-- ── 4. 댓글 수 카운터 (AFTER INSERT/DELETE) ───────────────────────────────
-- security definer: 댓글 작성자가 남의 글 행을 update할 권한이 없어도 카운터는 갱신돼야 한다.
create or replace function public.board_comment_count()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    update public.posts set comment_n = comment_n + 1 where id = new.post_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.posts set comment_n = greatest(comment_n - 1, 0) where id = old.post_id;
    return old;
  end if;
  return null;
end $$;

drop trigger if exists post_comments_count on public.post_comments;
create trigger post_comments_count
  after insert or delete on public.post_comments
  for each row execute function public.board_comment_count();

-- ── 5. RLS ───────────────────────────────────────────────────────────────
alter table public.posts enable row level security;

drop policy if exists posts_select on public.posts;
create policy posts_select on public.posts
  for select to authenticated using (true);

-- 커뮤니티: 로그인 유저 본인 명의. 공지: 관리자(학원)만.
drop policy if exists posts_insert on public.posts;
create policy posts_insert on public.posts
  for insert to authenticated
  with check (
    (board = 'community' and user_id = auth.uid())
    or (board = 'notice' and public.is_admin())
  );

-- 수정: 본인 또는 관리자. 본인 글을 공지로 승격하는 우회는 막는다.
drop policy if exists posts_update on public.posts;
create policy posts_update on public.posts
  for update to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (
    (user_id = auth.uid() or public.is_admin())
    and (board = 'community' or public.is_admin())
  );

drop policy if exists posts_delete on public.posts;
create policy posts_delete on public.posts
  for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());

alter table public.post_comments enable row level security;

drop policy if exists post_comments_select on public.post_comments;
create policy post_comments_select on public.post_comments
  for select to authenticated using (true);

drop policy if exists post_comments_insert on public.post_comments;
create policy post_comments_insert on public.post_comments
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists post_comments_delete on public.post_comments;
create policy post_comments_delete on public.post_comments
  for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());
